#    Copyright 2020, 2021, 2024 CodeMerx
#    This file is part of CodemerxDecompile.

#    CodemerxDecompile is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.

#    CodemerxDecompile is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#    GNU Affero General Public License for more details.

#    You should have received a copy of the GNU Affero General Public License
#    along with CodemerxDecompile.  If not, see<https://www.gnu.org/licenses/>.

name: CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  test-on-windows:
    runs-on: windows-2022

    steps:
    - name: Harden the runner
      uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
      with:
        use-policy-store: true
        api-key: ${{ secrets.STEP_SECURITY_API_KEY }}

    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

    - name: Setup DotNet
      uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
      with:
        dotnet-version: |
          2.x
          3.x
          5.x
          6.x
          7.x

    - name: Run Tests
      run: dotnet test -c Release
      working-directory: ./src/Decompiler.Tests
  
  test-on-linux:
    runs-on: ubuntu-22.04

    steps:
    - name: Harden the runner
      uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
      with:
        use-policy-store: true
        api-key: ${{ secrets.STEP_SECURITY_API_KEY }}

    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

    - name: Setup .NET
      uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
      with:
        dotnet-version: |
          6.x
          7.x

    - name: Run Tests
      run: dotnet test -c Release
      working-directory: ./src/Decompiler.Tests

  test-on-mac:
    runs-on: macos-13

    env:
      DOTNET_INSTALL_DIR: "/usr/local/share/dotnet"

    steps:
    - name: Harden the runner
      uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
      with:
        use-policy-store: true
        api-key: ${{ secrets.STEP_SECURITY_API_KEY }}

    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

    - name: Setup .NET
      uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
      with:
        dotnet-version: |
          6.x
          7.x

    - name: Run Tests
      run: dotnet test -c Release
      working-directory: ./src/Decompiler.Tests
